module.exports = {
  getReservedCampaignsCount: require('./getReservedCampaignsCount'),
  getCampaignsByWobject: require('./getCampaignsByWobject'),
  getEligibleCampaigns: require('./getEligibleCampaigns'),
  getReservedCampaigns: require('./getReservedCampigns'),
  getDataForFirstLoad: require('./getDataForFirstLoad'),
  getSuitableUsers: require('./getSuitableUsers'),
  getAllCampaigns: require('./getAllCampaigns'),
  checkingReview: require('./checkingReview'),
  getUserRewards: require('./getUserRewards'),
  createCampaign: require('./createCampaign'),
  getDashboard: require('./getDashboard'),
  getCampaign: require('./getCampaign'),
  getHistory: require('./getHistory'),
  getTabType: require('./getTabType'),
};
