module.exports = {
  CampaignFactory: require('./Campaign/CampaignFactory'),
  BlacklistFactory: require('./BlackList/blackListFactory'),
  PaymentFactory: require('./Campaign/PaymentFactory'),
  UserFactory: require('./User/UserFactory'),
  PostFactory: require('./Post/PostFactory'),
  WobjectFactory: require('./Wobject/WobjectFactory'),
  PaymentHistoryFactory: require('./PaymentHistory/PaymentHistoryFactory'),
  MatchBotFactory: require('./MatchBot/MatchBotFactory'),
  ExtendedMatchBotFactory: require('./MatchBot/ExtendedMatchBotFactory'),
  BotUpvoteFactory: require('./BotUpvote/BotUpvoteFactory'),
  ExchangeFactory: require('./InternalExchange/exchangeFactory'),
  AppFactory: require('./AppFactory/AppFactory'),
  SubscriptionFactory: require('./SubscriptionFactory/SubscriptionFactory'),
  AppendObjectFactory: require('./Wobject/AppendObjectFactory'),
  WobjectSubscriptionFactory: require('./WobjectSubscriptionFactory/WobjectSubscriptionFactory'),
  CurrenciesStatisticsFactory: require('./CurrenciesStatistics/CurrenciesStatisticsFactory'),
  CurrenciesRatesFactory: require('./CurrenciesRates/CurrenciesRatesFactory'),
};
